name: ci-docker-build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        required: true
        default: "0.1.0"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        service: ["element-api", "element-app"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: packages/${{ matrix.service }}/ 
          dockerfile: packages/${{ matrix.service }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_ACCOUNT }}/${{ matrix.service }}
          tags: ${{ github.event.inputs.tag }}